version: '3.7'

networks:
  roomsensor_bridge:
    name: roomsensor_bridge
    driver: bridge

services:
  # uwebsockets for socket connections
  rs_api_server:
    container_name: "rs_api_server"
    build:
      context: ./api
    ports:
      - 42069:42069
    networks:
      - roomsensor_bridge
    links:
        - rs_mongodb
    depends_on:
        - rs_mongodb
  rs_mongodb:
    image: mongo:latest
    container_name: "rs_mongodb"
    networks:
      - roomsensor_bridge
    command: [--auth]
    environment:
      - MONGODB_USERNAME=roomsensors
      - MONGODB_PASSWORD=AGnKOyUisUwI5PStZKjXvaRmzJEtUmwk
      - MONGODB_DATABASE=roomsensors
    volumes:
      - ./data/db:/data/db
    ports:
        - 27018:27018