version: '3.7'

networks:
  paaspop_bridge:
    name: express_bridge
    driver: bridge

services:
  # uwebsockets for socket connections
  api_server:
    build:
      context: ./api
    ports:
      - 42069:42069
    networks:
      - express_bridge
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    networks:
      - paaspop_bridge
    depends_on:
      - nginx
    environment:
      MYSQL_ROOT_PASSWORD: Q*+wGDhC8N_@Kw!7Vuw9b=YDwgeubm^z
      MYSQL_DATABASE: roomsensors
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mmEEEaQ*a%q!p89&szsa^bg9fBrD_#rt

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5876:5876
  # Nginx as firewall + port control?